[package]
name = "cce-model"
version = "0.1.0"
edition = "2021"

[dependencies]
cce-ui = { git = "https://github.com/lsgalante/cce-ui.git", rev = "d5b546acae0e8bf95bab8dc8cf7e6bd7ba80ac87" }
cce-mesh-io = { git = "https://github.com/lsgalante/cce-mesh-io.git", rev = "02e0b6fbcc30e92566522bb55c8e2ce18aed65ec" }
glam = "0.29"
log = "0.4"
env_logger = "0.11"
